language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install ./src

script:
  - chmod +x ./scripts/run_tests.sh
  - ./scripts/run_tests.sh

after_script:
  - coverage report > cov.txt
  - codecov
  